/**
 * 
 */
package edu.umaine.cs.cos515.max;

import java.io.InputStream;
import java.io.PrintStream;
import java.text.ParseException;
import java.util.Scanner;

import edu.umaine.cs.appletConsole.AppletConsoleProgram;

/**
 * <code>MaximaToJava</code> converts a subset of Maxima code directly into
 * Java syntax. This is convenient if a user is creating code that requires a
 * large expression that is generated by Maxima.
 * 
 * @author Mark Royer
 * 
 */
public class MaximaToJava implements AppletConsoleProgram {

    /**
     * The input stream for the program
     */
    private static InputStream in;

    /**
     * The output stream for the program
     */
    private static PrintStream out;

    /*
     * (non-Javadoc)
     * 
     * @see edu.umaine.cs.appletConsole.AppletConsoleProgram#setInputOutputStreams(java.io.InputStream,
     *      java.io.PrintStream)
     */
    public void setInputOutputStreams(InputStream in, PrintStream out) {
        MaximaToJava.in = in;
        MaximaToJava.out = out;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Runnable#run()
     */
    public void run() {

        Scanner scan = new Scanner(in);

        out.println("Converts simple Maxima equations to Java code.");
        out.println("Use at your own risk.");
        out.println("Enter Maxima equations one per line.");
        out.println("Enter \"\\done\" when finished.");
        out.println("**********************************************");
        out.println("**********************************************");
        out.println();

        String line = "";

        while (!"\\done".equals(line)) {
            line = scan.nextLine();
            try {
                out.println(Maxima.toJava(line));
            } catch (ParseException e) {
                out.println("There was an error parsing the last equation.");
                out.print(e.getMessage() + " at " + e.getErrorOffset());
                out.println();
            }
        }
        
        scan.close();
    }

    /**
     * Run in a terminal window
     * 
     * @param args
     */
    public static void main(String[] args) {
        new MaximaToJava().run();
    }

}
